//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListenAndWrite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Entity;

    public partial class audio
    {
        [Key]
        public int idAudio { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public string text { get; set; }
        public int idChuDe { get; set; }
    
        public virtual chude chudes { get; set; }
    }
}
